# Generated by Django 5.0.2 on 2024-03-28 18:00

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='avatars/avatar.jpg', force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[320, None], upload_to='avatars/'),
        ),
    ]
