# Generated by Django 5.0.2 on 2024-09-12 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_is_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('created_date',)},
        ),
        migrations.AlterModelOptions(
            name='postcomments',
            options={'ordering': ('timestamp',)},
        ),
    ]
