# Generated by Django 5.0.2 on 2024-03-17 14:04

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_friendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimages',
            name='images',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[700, None], upload_to='images'),
        ),
    ]
