# Generated by Django 5.0.2 on 2024-03-17 14:22

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_postimages_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimages',
            name='images',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[2680, None], upload_to='images'),
        ),
        migrations.AlterField(
            model_name='postvideos',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
