# Generated by Django 5.0.2 on 2024-04-02 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_postcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='api.post'),
        ),
    ]
