# Generated by Django 5.0.2 on 2024-03-30 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatlist',
            old_name='reated_at',
            new_name='created_at',
        ),
    ]
