# Generated by Django 5.0.2 on 2024-04-01 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_audiomessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatlist',
            options={'ordering': ['-updated_at']},
        ),
    ]
