# Generated by Django 5.0.2 on 2024-04-02 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chatlist_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiomessage',
            name='message',
        ),
        migrations.AddField(
            model_name='audiomessage',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_audio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audiomessage',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sent_audio', to=settings.AUTH_USER_MODEL),
        ),
    ]
