# Generated by Django 5.0.2 on 2024-04-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_audiomessage_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiomessage',
            name='duration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
