# Generated by Django 5.0.2 on 2024-04-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_audiomessage_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiomessage',
            name='duration',
            field=models.CharField(max_length=20),
        ),
    ]
