# Generated by Django 5.0.2 on 2024-04-02 11:49

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_imagemessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemessage',
            name='images',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[2680, None], upload_to='image_messages/'),
        ),
    ]
