# Generated by Django 5.0.2 on 2024-03-14 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendlist',
            old_name='friend',
            new_name='friends',
        ),
    ]
